# Generated by Django 4.2.3 on 2023-07-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter',
            name='skills',
        ),
        migrations.AlterField(
            model_name='renter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
