# Generated by Django 4.2.3 on 2023-08-01 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/car_categories')),
                ('is_active', models.BooleanField(default=True)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=500)),
                ('year_manufactured', models.PositiveIntegerField()),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_type', models.CharField(max_length=100)),
                ('transmission_type', models.CharField(max_length=100)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('air_conditioned', models.BooleanField(default=False)),
                ('power_windows', models.BooleanField(default=False)),
                ('central_locking', models.BooleanField(default=False)),
                ('audio_system', models.BooleanField(default=False)),
                ('gps_navigation', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=600)),
                ('image', models.ImageField(upload_to='photos/cars')),
                ('is_active', models.BooleanField(default=False)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carcategory')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
