# Generated by Django 4.2.3 on 2023-07-30 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0002_remove_renter_skills_alter_renter_is_active'),
        ('cars', '0002_alter_car_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='renter.renter'),
        ),
    ]
