# Generated by Django 4.2.3 on 2023-07-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_renter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='renter',
        ),
    ]
