# Generated by Django 4.2.3 on 2023-08-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='carslot',
            name='slot_duration',
        ),
        migrations.RemoveField(
            model_name='carslot',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='carslot',
            name='status',
        ),
    ]
