# Generated by Django 4.2.3 on 2023-08-11 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_product', models.CharField(max_length=100)),
                ('order_amount', models.CharField(max_length=25)),
                ('order_payment_id', models.CharField(max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('picked_up', 'Picked Up'), ('returned', 'Returned'), ('late', 'Late Return'), ('damage', 'Damage Reported')], default='pending', max_length=20)),
                ('booking_payment_id', models.CharField(max_length=100)),
                ('booking_order_id', models.CharField(max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('booking_date', models.DateTimeField(auto_now=True)),
                ('late_return_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('damage_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('dropoff_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_bookings', to='cars.location')),
                ('pickup_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_bookings', to='cars.location')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carslot')),
                ('user', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
