# Generated by Django 4.2.3 on 2023-08-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isPaid',
            new_name='is_paid',
        ),
    ]
