# Generated by Django 4.2.3 on 2023-08-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_ispaid_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='booking_order_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
