# Generated by Django 4.2.3 on 2023-08-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_carbooking_booking_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='damage_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='late_return_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('picked_up', 'Picked Up'), ('returned', 'Returned'), ('late', 'Late Return'), ('damage', 'Damage Reported')], default='pending', max_length=20),
        ),
    ]
